variable "env" {}
variable "location" {}
variable "address_space" {}
variable "subnets" {}
variable "default_rg_name" {}
variable "mysql-svc" {}
variable "redis-svc" {}
variable "mongodb-svc" {}
variable "servicebus-svc" {}
variable "aks-svc" {}
variable "acr-svc" {}
