variable "name" {}
variable "env" {}
variable "rg_name" {}
variable "rg_location" {}
variable "subnet_id" {}
variable "acr_id" {}
variable "vm_size" {}
variable "node_count" {}
variable "pod_cidr" {}
variable "service_cidr" {}
variable "dns_service_ip" {}
