sonar.projectKey=roboshop-catalogue
sonar.projectName=roboshop-catalogue
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
