sonar.projectKey=roboshop-ratings
sonar.projectName=roboshop-ratings
sonar.sources=app.py
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**,tests/**
