sonar.projectKey=roboshop-payment
sonar.projectName=roboshop-payment
sonar.sources=main.py
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**,tests/**
