sonar.projectKey=roboshop-cart
sonar.projectName=roboshop-cart
sonar.sources=server.js,metrics.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.exclusions=node_modules/**,coverage/**,test/**,**/*.test.js,jest.config.js,jest.integration.config.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
